### ISSUE TITLE
Since Update to WIN Server 2016 DC (14393.rs1_release.220610-1622) it don't work anymore

### ISSUE THREAD

**Issue by EmEiBee** [idstam/logview4net#5]
Since the last update, l4n can still be started, but the log window is no longer displayed.
If I start l4n, the "ConfigureSession" window also appears. If I select "FileListener" and then any log file and start, the icon remains on the bar, but no window opens.

In addition, ProcessExplorer reports:
- 1 security vendor and no sandboxes flagged this file as malicious
- Downloader.DownloaderGuideCRTD.Win32.

**Comment by idstam** [comment]
I haven't touched this since November 2019 and that's the only release here on GitHub.
I used to use an installer that were flagged as malicious, but that was years ago. Now it's just a zip file with the binaries.
I will probably not do anything about it, but please let me know what version you are trying out and where you found it.

**Comment by EmEiBee** [comment]
The EXE show me V13.34.0.0, last modified 19.08.2013 09:49
I have download it here: https://sourceforge.net/projects/logview4net/

**Comment by idstam** [comment]
Oh, that's an old one. Please try the under under releases here oh Github instead.

**Comment by EmEiBee** [comment]
Ok, I have seen that the sourceforge file is ugly old and haven't noticed that the file here are the newest one...
That's a trap for those the search-engines link to sourceforce first ;o)

Ty for assistance and TC
